server:
  port: 8084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: company-service
          uri: lb://companyms
          predicates:
            - Path=/companies/**
        - id: job-service
          uri: lb://jobms
          predicates:
            - Path=/jobs/**
        - id: review-service
          uri: lb://reviewms
          predicates:
            - Path=/reviews/**

  zipkin:
    base-url: http://localhost:9411/

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
